# Generated by Django 5.0.6 on 2024-08-08 11:38

import game_model.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_model', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='expiration_time',
            field=models.DateTimeField(default=game_model.utils.default_expiration_time),
        ),
        migrations.AddField(
            model_name='game',
            name='game_name',
            field=models.CharField(default='Unnamed Game', max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
