# Generated by Django 5.0.6 on 2024-08-16 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_model', '0002_game_expiration_time_game_game_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='expiration_time',
            field=models.DurationField(),
        ),
    ]
