# Generated by Django 5.0.6 on 2024-08-16 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_model', '0003_game_created_at_alter_game_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='expiration_time',
            field=models.DurationField(default=datetime.timedelta(seconds=1)),
        ),
    ]
